FROM node:8

RUN npm install -g elm-format@0.8.5 --unsafe-perm=true
ADD create-elm-app /usr/lib/node_modules/create-elm-app
RUN cd /usr/lib/node_modules/create-elm-app/ && npm link

WORKDIR /source

EXPOSE 3000
